[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/"
  to = "/hu/"
  status = 302
  force = true

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_BASE_URL = "https://sectorhungaricus.com"